Lab2 готово проверяйте
neckbosov/scala-telegram-bot-cats pull request #1
Opened 2020-03-02 14:41 UTC by neckbosov

2020-03-24 07:19 UTC, eld0727 requested changes

2020-03-24 07:19 UTC, eld0727 commented on src/main/scala/Example.scala
> +object Example {
Кажется это можно удалить

2020-03-24 07:19 UTC, eld0727 commented on src/main/scala/BotStarter.scala
> +class Service(val apikey: String)(implicit val backend: SttpBackend[Future, Nothing], implicit val ec: ExecutionContext) {
Всё что касается сервиса лучше вынести в отдельный файл

2020-03-24 07:19 UTC, eld0727 commented on src/main/scala/BotStarter.scala
> +  private implicit val serialization: Serialization.type = org.json4s.native.Serialization
Лучше тоже вынести в аргументы сервиса

2020-04-02 12:51 UTC, neckbosov commented on src/main/scala/Example.scala
> +object Example {
Исправлено в lab4

2020-04-02 12:52 UTC, neckbosov commented on src/main/scala/BotStarter.scala
> +class Service(val apikey: String)(implicit val backend: SttpBackend[Future, Nothing], implicit val ec: ExecutionContext) {
Исправлено в lab4

2020-04-02 12:52 UTC, neckbosov commented on src/main/scala/BotStarter.scala
> +  private implicit val serialization: Serialization.type = org.json4s.native.Serialization
Исправлено в lab4

2020-04-02 12:52 UTC, merged